FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
ENV NODE_ENV=development \
    NPM_CONFIG_PRODUCTION=false
RUN npm ci --include=dev

FROM node:22-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
